version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: ['uvicorn', 'src.main:app', '--host', '0.0.0.0', '--port', '8000']
    ports:
      - '8000:8000'
    env_file: .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: '${MONGO_CONNECTION_STRING}'

  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    command: [ 'redis-server', '--save', '20', '1' ]
    expose:
      - '6379'
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: